name: Prova

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: echo "hello" > ${{ github.workspace }}/txt.txt
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.1
      with:
        path: . 
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1.9.0
      with:
        artifacts: 'release.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: 'release'
        path: 'release.zip'
