name: Prova

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: echo "hello" > ${{ github.workspace }}/txt.txt
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r result.zip *.cpp
    - uses: actions/upload-artifact@v2
      with:
        name: result.zip
    
    
